'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8943
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
Partial Public Class loadconfig

    Private notifyerrorField As ftpconfigNotifyerror
    '''<remarks/>
    Public Property notifyerror() As ftpconfigNotifyerror
        Get
            Return Me.notifyerrorField
        End Get
        Set
            Me.notifyerrorField = Value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ftpconfigNotifyerror

    Private notifyField() As ftpconfigNotifyerrorNotify

    Private smtpField As String

    Private fromField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("notify")>
    Public Property notify() As ftpconfigNotifyerrorNotify()
        Get
            Return Me.notifyField
        End Get
        Set
            Me.notifyField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property smtp() As String
        Get
            Return Me.smtpField
        End Get
        Set
            Me.smtpField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property from() As String
        Get
            Return Me.fromField
        End Get
        Set
            Me.fromField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ftpconfigNotifyerrorNotify

    Private addressField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property address() As String
        Get
            Return Me.addressField
        End Get
        Set
            Me.addressField = Value
        End Set
    End Property

End Class
