'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9151
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class ftpconfig
    
    Private modeField As ftpconfigMode
    
    Private serverField As ftpconfigServer
    
    Private mode1Field As String
    
    '''<remarks/>
    Public Property mode() As ftpconfigMode
        Get
            Return Me.modeField
        End Get
        Set
            Me.modeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property server() As ftpconfigServer
        Get
            Return Me.serverField
        End Get
        Set
            Me.serverField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("mode")>  _
    Public Property mode1() As String
        Get
            Return Me.mode1Field
        End Get
        Set
            Me.mode1Field = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class ftpconfigMode

    Private actField As New List(Of ftpconfigModeAct)

    Private nameField As String
    
    Private serverField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("receive", GetType(ftpconfigModeReceive)),
     System.Xml.Serialization.XmlElementAttribute("send", GetType(ftpconfigModeSend))>
    Public Property Act() As List(Of ftpconfigModeAct)
        Get
            Return Me.actField
        End Get
        Set
            Me.actField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property server() As String
        Get
            Return Me.serverField
        End Get
        Set
            Me.serverField = value
        End Set
    End Property

End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ftpconfigModeAct

    Private dirField As String

    Private filespecField As String

    Private remotedirField As String

    '''<remarks/>
    Public Property dir() As String
        Get
            Return Me.dirField
        End Get
        Set
            Me.dirField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property filespec() As String
        Get
            Return Me.filespecField
        End Get
        Set
            Me.filespecField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property remotedir() As String
        Get
            Return Me.remotedirField
        End Get
        Set
            Me.remotedirField = Value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class ftpconfigModeReceive
    Inherits ftpconfigModeAct

    Private deleteField As Boolean

    Private binField As String

    Private environmentField As String

    '''<remarks/>
    Public Property delete() As Boolean
        Get
            Return Me.deleteField
        End Get
        Set
            Me.deleteField = value
        End Set
    End Property

    '''<remarks/>
    Public Property bin() As String
        Get
            Return Me.binField
        End Get
        Set
            Me.binField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property environment() As String
        Get
            Return Me.environmentField
        End Get
        Set
            Me.environmentField = value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class ftpconfigModeSend
    Inherits ftpconfigModeAct

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class ftpconfigServer
    
    Private hostNameField As String
    
    Private protocolField As String
    
    Private transferModeField As String
    
    Private userNameField As String
    
    Private passwordField As UInteger
    
    Private sshHostKeyFingerprintField As String
    
    Private portField As Byte
    
    Private nameField As String
    
    '''<remarks/>
    Public Property HostName() As String
        Get
            Return Me.hostNameField
        End Get
        Set
            Me.hostNameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Protocol() As String
        Get
            Return Me.protocolField
        End Get
        Set
            Me.protocolField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TransferMode() As String
        Get
            Return Me.transferModeField
        End Get
        Set
            Me.transferModeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property UserName() As String
        Get
            Return Me.userNameField
        End Get
        Set
            Me.userNameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Password() As UInteger
        Get
            Return Me.passwordField
        End Get
        Set
            Me.passwordField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SshHostKeyFingerprint() As String
        Get
            Return Me.sshHostKeyFingerprintField
        End Get
        Set
            Me.sshHostKeyFingerprintField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Port() As Byte
        Get
            Return Me.portField
        End Get
        Set
            Me.portField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
End Class
