'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8943
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class table

    Private colField As List(Of tableCol)

    Private table1Field() As table

    Private nameField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("col")>
    Public Property col() As List(Of tableCol)
        Get
            Return Me.colField
        End Get
        Set
            Me.colField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("table")>
    Public Property subtable() As table()
        Get
            Return Me.table1Field
        End Get
        Set
            Me.table1Field = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property

    Private dbField As String
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property db() As String
        Get
            Return Me.dbField
        End Get
        Set
            Me.dbField = Value
        End Set
    End Property

    Private connectionStringField As String
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property connectionString() As String
        Get
            Return Me.connectionStringField
        End Get
        Set
            Me.connectionStringField = Value
        End Set
    End Property


End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class tableCol
    
    Private lineField As Byte
    
    Private nameField As String

    Private widthField As Integer

    Private widthFieldSpecified As Boolean

    Sub New()

    End Sub

    Sub New(line As Integer, Name As String, Optional width As Integer = 0)

        lineField = line
        nameField = Name
        widthFieldSpecified = Not (width = 0)

    End Sub
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property line() As Byte
        Get
            Return Me.lineField
        End Get
        Set
            Me.lineField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property width() As Integer
        Get
            If widthSpecified Then
                Return Me.widthField
            Else
                Return 0
            End If

        End Get
        Set
            Me.widthField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property widthSpecified() As Boolean
        Get
            Return Me.widthFieldSpecified
        End Get
        Set
            Me.widthFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
Partial Public Class makeconfig

    Private outputField() As makeconfigOutput

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("output")>
    Public Property output() As makeconfigOutput()
        Get
            Return Me.outputField
        End Get
        Set
            Me.outputField = Value
        End Set
    End Property

    Private connectionStringField As String
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property connectionString() As String
        Get
            Return Me.connectionStringField
        End Get
        Set
            Me.connectionStringField = Value
        End Set
    End Property

    Private dbField As String
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property db() As String
        Get
            Return Me.dbField
        End Get
        Set
            Me.dbField = Value
        End Set
    End Property

    Private notifyerrorField As ftpconfigNotifyerror
    '''<remarks/>
    Public Property notifyerror() As ftpconfigNotifyerror
        Get
            Return Me.notifyerrorField
        End Get
        Set
            Me.notifyerrorField = Value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class makeconfigOutput
    
    Private tableField() As table
    
    Private filespecField As String
    
    Private deliminatorField As String

    Private lineendField As String

    Private EncodingField As String

    Private runcountfield As String

    Private formatfield As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("table")>  _
    Public Property table() As table()
        Get
            Return Me.tableField
        End Get
        Set
            Me.tableField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property filespec() As String
        Get
            Return Me.filespecField
        End Get
        Set
            Me.filespecField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property deliminator() As String
        Get
            If Not deliminatorField Is Nothing Then
                Return Me.deliminatorField
            Else
                Return ","
            End If
        End Get
        Set
            Me.deliminatorField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property lineend() As String
        Get
            If Not lineendField Is Nothing Then
                Return Me.lineendField
            Else
                Return "crlf"
            End If

        End Get
        Set
            Me.lineendField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property encoding() As String
        Get
            Return Me.EncodingField
        End Get
        Set
            Me.EncodingField = Value
        End Set
    End Property

    Public ReadOnly Property sEncoding As Text.Encoding
        Get
            Select Case Encoding.ToUpper
                Case "ASCII"
                    Return Text.Encoding.ASCII
                Case "UNICODE"
                    Return Text.Encoding.Unicode
                Case "UTF32"
                    Return Text.Encoding.UTF32
                Case "UTF7"
                    Return Text.Encoding.UTF7
                Case "UTF8"
                    Return Text.Encoding.UTF8
                Case "BIGENDIANUNICODE"
                    Return Text.Encoding.BigEndianUnicode
                Case Else
                    Return Text.Encoding.ASCII

            End Select
        End Get
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property runcount() As String
        Get
            If runcountfield Is Nothing Then
                Return 1
            Else
                Return Me.runcountfield
            End If

        End Get
        Set
            Me.runcountfield = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property format() As String
        Get
            Return Me.formatfield
        End Get
        Set
            Me.formatfield = Value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ftpconfigNotifyerror

    Private notifyField() As ftpconfigNotifyerrorNotify

    Private smtpField As String

    Private fromField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("notify")>
    Public Property notify() As ftpconfigNotifyerrorNotify()
        Get
            Return Me.notifyField
        End Get
        Set
            Me.notifyField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property smtp() As String
        Get
            Return Me.smtpField
        End Get
        Set
            Me.smtpField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property from() As String
        Get
            Return Me.fromField
        End Get
        Set
            Me.fromField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ftpconfigNotifyerrorNotify

    Private addressField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property address() As String
        Get
            Return Me.addressField
        End Get
        Set
            Me.addressField = Value
        End Set
    End Property

End Class
