'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8943
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class ftpconfig
    
    Private modeField() As ftpconfigMode

    Private serverField() As ftpconfigServer

    Private notifyerrorField As ftpconfigNotifyerror

    Private mode1Field As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mode")>
    Public Property mode() As ftpconfigMode()
        Get
            Return Me.modeField
        End Get
        Set
            Me.modeField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("server")>
    Public Property server() As ftpconfigServer()
        Get
            Return Me.serverField
        End Get
        Set
            Me.serverField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property notifyerror() As ftpconfigNotifyerror
        Get
            Return Me.notifyerrorField
        End Get
        Set
            Me.notifyerrorField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("mode")>
    Public Property defaultmode() As String
        Get
            Return Me.mode1Field
        End Get
        Set
            Me.mode1Field = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ftpconfigMode

    Private actField() As ftpconfigModeAct

    Private nameField As String

    Private serverField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("act")>
    Public Property act() As ftpconfigModeAct()
        Get
            Return Me.actField
        End Get
        Set
            Me.actField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property server() As String
        Get
            Return Me.serverField
        End Get
        Set
            Me.serverField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ftpconfigModeAct

    Private dirField As String

    Private filespecField As String

    Private remotedirField As String

    Private deleteField As Byte

    Private deleteFieldSpecified As Boolean

    Private typeField As String

    Private binField As String

    '''<remarks/>
    Public Property dir() As String
        Get
            Return Me.dirField
        End Get
        Set
            Me.dirField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property filespec() As String
        Get
            Return Me.filespecField
        End Get
        Set
            Me.filespecField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property remotedir() As String
        Get
            Return Me.remotedirField
        End Get
        Set
            Me.remotedirField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property delete() As Byte
        Get
            Return Me.deleteField
        End Get
        Set
            Me.deleteField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property deleteSpecified() As Boolean
        Get
            Return Me.deleteFieldSpecified
        End Get
        Set
            Me.deleteFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = Value
        End Set
    End Property

    Public Enum eType
        send
        receive
    End Enum

    Public ReadOnly Property stype() As eType
        Get
            Select Case Me.typeField.ToLower
                Case "send"
                    Return eType.send
                Case Else
                    Return eType.receive

            End Select
        End Get
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property bin() As String
        Get
            If Not Me.binField Is Nothing Then
                If Me.binField.Length = 0 Then Return Nothing
            End If
            Return Me.binField
        End Get
        Set
            Me.binField = Value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ftpconfigServer

    Private hostNameField As String

    Private protocolField As String

    Private transferModeField As String

    Private userNameField As String

    Private passwordField As String

    Private sshHostKeyFingerprintField As String

    Private nameField As String

    Private PortField As Integer = -1

    '''<remarks/>
    Public Property HostName() As String
        Get
            Return Me.hostNameField
        End Get
        Set
            Me.hostNameField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Protocol() As String
        Get
            Return Me.protocolField
        End Get
        Set
            Me.protocolField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property TransferMode() As String
        Get
            Return Me.transferModeField
        End Get
        Set
            Me.transferModeField = Value
        End Set
    End Property

    Public Property sProtocol() As Integer
        Get
            Select Case Me.protocolField.ToLower
                Case "webdav"
                    Return 3

                Case "s3"
                    Return 4

                Case "scp"
                    Return 1

                Case "sftp"
                    Return 0

                Case "tls"
                    Return 5

                Case Else
                    Return 2


            End Select

        End Get
        Set
            Select Case Value
                Case 3
                    Me.protocolField = "Webdav"

                Case 4
                    Me.protocolField = "S3"

                Case 1
                    Me.protocolField = "Scp"

                Case 0
                    Me.protocolField = "Sftp"

                Case 5
                    Me.protocolField = "TLS"

                Case Else
                    Me.protocolField = "Ftp"


            End Select
        End Set
    End Property

    '''<remarks/>
    Public Property sTransferMode() As WinSCP.TransferMode
        Get
            Select Case Me.transferModeField.ToLower
                Case "ascii"
                    Return WinSCP.TransferMode.Ascii
                Case "binary"
                    Return WinSCP.TransferMode.Binary
                Case Else
                    Return WinSCP.TransferMode.Automatic
            End Select
        End Get
        Set
            Select Case Value
                Case WinSCP.TransferMode.Ascii
                    Me.transferModeField = "Ascii"
                Case WinSCP.TransferMode.Binary
                    Me.transferModeField = "Binary"
                Case Else
                    Me.transferModeField = "Automatic"
            End Select

        End Set
    End Property

    '''<remarks/>
    Public Property UserName() As String
        Get
            Return Me.userNameField
        End Get
        Set
            Me.userNameField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Password() As String
        Get
            Return Me.passwordField
        End Get
        Set
            Me.passwordField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property SshHostKeyFingerprint() As String
        Get
            Return Me.sshHostKeyFingerprintField
        End Get
        Set
            Me.sshHostKeyFingerprintField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

    '''<remarks/>    
    Public Property Port As Integer
        Get
            Return PortField
        End Get
        Set(value As Integer)
            PortField = value
        End Set
    End Property

End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ftpconfigNotifyerror

    Private notifyField() As ftpconfigNotifyerrorNotify

    Private smtpField As String

    Private fromField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("notify")>
    Public Property notify() As ftpconfigNotifyerrorNotify()
        Get
            Return Me.notifyField
        End Get
        Set
            Me.notifyField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property smtp() As String
        Get
            Return Me.smtpField
        End Get
        Set
            Me.smtpField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property from() As String
        Get
            Return Me.fromField
        End Get
        Set
            Me.fromField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class ftpconfigNotifyerrorNotify

    Private addressField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property address() As String
        Get
            Return Me.addressField
        End Get
        Set
            Me.addressField = Value
        End Set
    End Property

End Class
