Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: ALINEEMP as List(Of rowALINEEMP)
''' Date: 20/03/2020
'''
''' </summary>
<oFormClass("rowALINEEMP")>
Public Class ALINEEMP : Inherits oForm

    ''' <summary>
    ''' ALINEEMP Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the ALINEEMP form.
    ''' </summary>
    ''' <returns>rowALINEEMP</returns>
    Public Function AddRow() As rowALINEEMP
        With Me
            .Add(New rowALINEEMP(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the ALINEEMP form.
''' </summary>
<oRowClass("ALINEEMP", "serialALINEEMP")>
Public Class rowALINEEMP : Inherits oRow

    ''' <summary>
    ''' rowALINEEMP Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Employee ID" Value of ALINEEMP.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Employee ID")>
    Public Property USERID As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Employee Name" Value of ALINEEMP.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Employee Name", ReadOnly:=True, length:=30)>
    Public Readonly Property BNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Start Labor" Value of ALINEEMP.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Start Labor", length:=5)>
    Public Property STIME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "End Labor" Value of ALINEEMP.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("End Labor", length:=5)>
    Public Property ETIME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Span" Value of ALINEEMP.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Span", length:=6)>
    Public Property ASPAN As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Shift" Value of ALINEEMP.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Shift", length:=8)>
    Public Property SHIFTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Key Line" Value of ALINEEMP.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Key Line", Key:=True)>
    Public Property KLINE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowALINEEMP.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialALINEEMP 

    Public Property USERID As Integer?
    Public Property BNAME As String
    Public Property STIME As String
    Public Property ETIME As String
    Public Property ASPAN As String
    Public Property SHIFTNAME As String
    Public Property KLINE As Integer?


End Class