Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: CURREG as List(Of rowCURREG)
''' Date: 20/03/2020
'''
''' </summary>
<oFormClass("rowCURREG", "CURREGITEMS")>
Public Class CURREG : Inherits oForm

    ''' <summary>
    ''' CURREG Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the CURREG form.
    ''' </summary>
    ''' <returns>rowCURREG</returns>
    Public Function AddRow() As rowCURREG
        With Me
            .Add(New rowCURREG(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the CURREG form.
''' </summary>
<oRowClass("CURREG", "serialCURREG")>
Public Class rowCURREG : Inherits oRow

    ''' <summary>
    ''' rowCURREG Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get/set the CURREGITEMS subform.
    ''' </summary>
    ''' <returns>CURREGITEMS</returns>
	Public Property CURREGITEMS As CURREGITEMS
        Get
            Return MyBase.SubForms("CURREGITEMS")
        End Get
        Set(value As CURREGITEMS)
            MyBase.SubForms("CURREGITEMS") = value
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Date" Value of CURREG.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Date", Key:=True, mandatory:=True)>
    Public Property CURDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Day" Value of CURREG.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Day", length:=3)>
    Public Property DAY As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowCURREG.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialCURREG 

    Public Property CURDATE As Date?
    Public Property DAY As String


End Class