Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: DOCUMENTS_A as List(Of rowDOCUMENTS_A)
''' Date: 20/03/2020
'''
''' </summary>
<oFormClass("rowDOCUMENTS_A", "TRANSORDER_A", "DOCPACK")>
Public Class DOCUMENTS_A : Inherits oForm

    ''' <summary>
    ''' DOCUMENTS_A Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the DOCUMENTS_A form.
    ''' </summary>
    ''' <returns>rowDOCUMENTS_A</returns>
    Public Function AddRow() As rowDOCUMENTS_A
        With Me
            .Add(New rowDOCUMENTS_A(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the DOCUMENTS_A form.
''' </summary>
<oRowClass("DOCUMENTS_A", "serialDOCUMENTS_A")>
Public Class rowDOCUMENTS_A : Inherits oRow

    ''' <summary>
    ''' rowDOCUMENTS_A Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get/set the TRANSORDER_A subform.
    ''' </summary>
    ''' <returns>TRANSORDER_A</returns>
	Public Property TRANSORDER_A As TRANSORDER_A
        Get
            Return MyBase.SubForms("TRANSORDER_A")
        End Get
        Set(value As TRANSORDER_A)
            MyBase.SubForms("TRANSORDER_A") = value
        End Set
    End Property    
	''' <summary>
    ''' Get/set the DOCPACK subform.
    ''' </summary>
    ''' <returns>DOCPACK</returns>
	Public Property DOCPACK As DOCPACK
        Get
            Return MyBase.SubForms("DOCPACK")
        End Get
        Set(value As DOCPACK)
            MyBase.SubForms("DOCPACK") = value
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Customer Number" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer Number", mandatory:=True, length:=16)>
    Public Property CUSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Customer Name" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer Name", ReadOnly:=True, length:=48)>
    Public Readonly Property CDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Original Warehouse" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Original Warehouse", mandatory:=True, length:=4)>
    Public Property WARHSNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Date" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Date", mandatory:=True)>
    Public Property CURDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Packing Slip Number" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Packing Slip Number", ReadOnly:=True, Key:=True, length:=16)>
    Public Readonly Property DOCNO As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Rep's Doc." Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Rep's Doc.", length:=16)>
    Public Property BOOKNUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Status" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Status", mandatory:=True, length:=12)>
    Public Property STATDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Assigned to" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Assigned to", mandatory:=True, length:=20)>
    Public Property OWNERLOGIN As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "For Order" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("For Order", length:=16)>
    Public Property ORDNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "RMA for Order" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("RMA for Order", ReadOnly:=True, length:=16)>
    Public Readonly Property ORDRMADOCNUM As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Customer's Purch Ord" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer's Purch Ord", ReadOnly:=True, length:=15)>
    Public Readonly Property REFERENCE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Details" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Details", length:=24)>
    Public Property DETAILS As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Document Code" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Document Code", ReadOnly:=True, length:=4)>
    Public Readonly Property DOCCODE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Included in Document" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Included in Document", ReadOnly:=True, length:=16)>
    Public Readonly Property TODOREFA As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Original Bin" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Original Bin", mandatory:=True, length:=14)>
    Public Property LOCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Orig. Warehouse Desc" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Orig. Warehouse Desc", ReadOnly:=True, length:=32)>
    Public Readonly Property WARHSDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Current Warehouse" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Current Warehouse", ReadOnly:=True, length:=4)>
    Public Readonly Property WARHSNAMENOW As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Current Bin" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Current Bin", ReadOnly:=True, length:=14)>
    Public Readonly Property LOCNAMENOW As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Current Warehs Desc." Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Current Warehs Desc.", ReadOnly:=True, length:=32)>
    Public Readonly Property WARHSDESNOW As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Crate Type Code" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Crate Type Code", length:=2)>
    Public Property PACKCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Crate Type Desc." Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Crate Type Desc.", ReadOnly:=True, length:=8)>
    Public Readonly Property PACKNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Manual Gross Weight" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Manual Gross Weight")>
    Public Property MWEIGHT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Auto Gross Weight" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Auto Gross Weight", ReadOnly:=True)>
    Public Readonly Property WEIGHT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Difference" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Difference", ReadOnly:=True)>
    Public Readonly Property WEIGHTDIFF As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Auto Net Weight" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Auto Net Weight", ReadOnly:=True)>
    Public Readonly Property NWEIGHT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Volume" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Volume", ReadOnly:=True)>
    Public Readonly Property VOLUME As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Unit" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Unit", ReadOnly:=True, length:=3)>
    Public Readonly Property VUNITNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Tracking Number" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Tracking Number", length:=20)>
    Public Property AIRWAYBILL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Shipping Pallet" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Shipping Pallet", length:=16)>
    Public Property BOXNUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Project Number" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Project Number", length:=16)>
    Public Property PROJDOCNO As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Project Description" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Project Description", ReadOnly:=True, length:=32)>
    Public Readonly Property PROJDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Branch Code" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Branch Code", length:=6)>
    Public Property BRANCHNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Branch Name" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Branch Name", ReadOnly:=True, length:=32)>
    Public Readonly Property BRANCHDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Parent's Serial No." Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Parent's Serial No.", length:=20)>
    Public Property PARENTSERNUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Number" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Number", length:=15)>
    Public Property PARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Part Description" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Description", ReadOnly:=True, length:=48)>
    Public Readonly Property PARTDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Print Part Attachmts" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Print Part Attachmts", length:=1)>
    Public Property INCPARTEXT As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Signature" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Signature", ReadOnly:=True, length:=20)>
    Public Readonly Property USERLOGIN As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Time Stamp" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Time Stamp", ReadOnly:=True)>
    Public Readonly Property UDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Delivery Date" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Delivery Date")>
    Public Property DISTRDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Document (ID)" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Document (ID)")>
    Public Property DOC As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Type" Value of DOCUMENTS_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Type", Key:=True, length:=1)>
    Public Property TYPE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowDOCUMENTS_A.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialDOCUMENTS_A 

    Public Property CUSTNAME As String
    Public Property CDES As String
    Public Property WARHSNAME As String
    Public Property CURDATE As Date?
    Public Property DOCNO As String
    Public Property BOOKNUM As String
    Public Property STATDES As String
    Public Property OWNERLOGIN As String
    Public Property ORDNAME As String
    Public Property ORDRMADOCNUM As String
    Public Property REFERENCE As String
    Public Property DETAILS As String
    Public Property DOCCODE As String
    Public Property TODOREFA As String
    Public Property LOCNAME As String
    Public Property WARHSDES As String
    Public Property WARHSNAMENOW As String
    Public Property LOCNAMENOW As String
    Public Property WARHSDESNOW As String
    Public Property PACKCODE As String
    Public Property PACKNAME As String
    Public Property MWEIGHT As Decimal?
    Public Property WEIGHT As Decimal?
    Public Property WEIGHTDIFF As Decimal?
    Public Property NWEIGHT As Decimal?
    Public Property VOLUME As Decimal?
    Public Property VUNITNAME As String
    Public Property AIRWAYBILL As String
    Public Property BOXNUM As String
    Public Property PROJDOCNO As String
    Public Property PROJDES As String
    Public Property BRANCHNAME As String
    Public Property BRANCHDES As String
    Public Property PARENTSERNUM As String
    Public Property PARTNAME As String
    Public Property PARTDES As String
    Public Property INCPARTEXT As String
    Public Property USERLOGIN As String
    Public Property UDATE As Date?
    Public Property DISTRDATE As Date?
    Public Property DOC As Integer?
    Public Property TYPE As String


End Class