Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: ECOPART as List(Of rowECOPART)
''' Date: 21/01/2020
'''
''' </summary>
<oFormClass("rowECOPART", "REVISIONS", "PARTREV")>
Public Class ECOPART : Inherits oForm

    ''' <summary>
    ''' ECOPART Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the ECOPART form.
    ''' </summary>
    ''' <returns>rowECOPART</returns>
    Public Function AddRow() As rowECOPART
        With Me
            .Add(New rowECOPART(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the ECOPART form.
''' </summary>
<oRowClass("ECOPART", "serialECOPART")>
Public Class rowECOPART : Inherits oRow

    ''' <summary>
    ''' rowECOPART Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get/set the REVISIONS subform.
    ''' </summary>
    ''' <returns>REVISIONS</returns>
	Public Property REVISIONS As REVISIONS
        Get
            Return MyBase.SubForms("REVISIONS")
        End Get
        Set(value As REVISIONS)
            MyBase.SubForms("REVISIONS") = value
        End Set
    End Property    
	''' <summary>
    ''' Get/set the PARTREV subform.
    ''' </summary>
    ''' <returns>PARTREV</returns>
	Public Property PARTREV As PARTREV
        Get
            Return MyBase.SubForms("PARTREV")
        End Get
        Set(value As PARTREV)
            MyBase.SubForms("PARTREV") = value
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Number" Value of ECOPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Number", length:=15)>
    Public Property PARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Part Description" Value of ECOPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Description", ReadOnly:=True, length:=48)>
    Public Readonly Property PARTDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Signature" Value of ECOPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Signature", ReadOnly:=True, length:=20)>
    Public Readonly Property USERLOGIN As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Time Stamp" Value of ECOPART.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Time Stamp", ReadOnly:=True)>
    Public Readonly Property UDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Key Line" Value of ECOPART.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Key Line", Key:=True)>
    Public Property KLINE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowECOPART.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialECOPART 

    Public Property PARTNAME As String
    Public Property PARTDES As String
    Public Property USERLOGIN As String
    Public Property UDATE As Date?
    Public Property KLINE As Integer?


End Class