Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: ECOREASONS as List(Of rowECOREASONS)
''' Date: 20/03/2020
'''
''' </summary>
<oFormClass("rowECOREASONS")>
Public Class ECOREASONS : Inherits oForm

    ''' <summary>
    ''' ECOREASONS Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the ECOREASONS form.
    ''' </summary>
    ''' <returns>rowECOREASONS</returns>
    Public Function AddRow() As rowECOREASONS
        With Me
            .Add(New rowECOREASONS(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the ECOREASONS form.
''' </summary>
<oRowClass("ECOREASONS", "serialECOREASONS")>
Public Class rowECOREASONS : Inherits oRow

    ''' <summary>
    ''' rowECOREASONS Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Reason Code" Value of ECOREASONS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Reason Code", Key:=True, length:=3)>
    Public Property ECOREASONCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Reason for ECO" Value of ECOREASONS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Reason for ECO", length:=32)>
    Public Property ECOREASONDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "ECO Reason (ID)" Value of ECOREASONS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("ECO Reason (ID)")>
    Public Property ECOREASON As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowECOREASONS.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialECOREASONS 

    Public Property ECOREASONCODE As String
    Public Property ECOREASONDES As String
    Public Property ECOREASON As Integer?


End Class