Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: LOGPART as List(Of rowLOGPART)
''' Date: 21/01/2020
'''
''' </summary>
<oFormClass("rowLOGPART", "PARTARC")>
Public Class LOGPART : Inherits oForm

    ''' <summary>
    ''' LOGPART Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the LOGPART form.
    ''' </summary>
    ''' <returns>rowLOGPART</returns>
    Public Function AddRow() As rowLOGPART
        With Me
            .Add(New rowLOGPART(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the LOGPART form.
''' </summary>
<oRowClass("LOGPART", "serialLOGPART")>
Public Class rowLOGPART : Inherits oRow

    ''' <summary>
    ''' rowLOGPART Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get/set the PARTARC subform.
    ''' </summary>
    ''' <returns>PARTARC</returns>
	Public Property PARTARC As PARTARC
        Get
            Return MyBase.SubForms("PARTARC")
        End Get
        Set(value As PARTARC)
            MyBase.SubForms("PARTARC") = value
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Number" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Number", Key:=True, mandatory:=True, length:=15)>
    Public Property PARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Bar Code" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bar Code", length:=16)>
    Public Property BARCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Description" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Description", mandatory:=True, length:=48)>
    Public Property PARTDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Desc. (Lang 2)" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Desc. (Lang 2)", length:=48)>
    Public Property EPARTDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Status" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Status", mandatory:=True, length:=12)>
    Public Property STATDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Type (P/R/O)" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Type (P/R/O)", mandatory:=True, length:=1)>
    Public Property TYPE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Inventory Control?" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Inventory Control?", length:=1)>
    Public Property INVFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Change Part Descrip." Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Change Part Descrip.", length:=1)>
    Public Property NSFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Maintain Serial Nos?" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Maintain Serial Nos?", length:=1)>
    Public Property SERNFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Purch'd via Web Site" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Purch'd via Web Site", length:=1)>
    Public Property SHOWINWEB As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Assigned to" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Assigned to", mandatory:=True, length:=20)>
    Public Property OWNERLOGIN As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Date Opened" Value of LOGPART.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Date Opened", ReadOnly:=True)>
    Public Readonly Property CREATEDDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Buy/Sell Unit" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Buy/Sell Unit", mandatory:=True, length:=3)>
    Public Property PUNITNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Factory Unit" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Factory Unit", mandatory:=True, length:=3)>
    Public Property UNITNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Picture" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Picture", length:=80)>
    Public Property EXTFILENAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Conversion Ratio" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Conversion Ratio", mandatory:=True)>
    Public Property CONV As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Variable Conversion" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Variable Conversion", length:=1)>
    Public Property NOTFIXEDCONV As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Family" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Family", mandatory:=True, length:=8)>
    Public Property FAMILYNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Family Description" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Family Description", ReadOnly:=True, length:=32)>
    Public Readonly Property FAMILYDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Family Type Code" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Family Type Code", ReadOnly:=True, length:=4)>
    Public Readonly Property FTCODE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Family Type Descrip." Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Family Type Descrip.", ReadOnly:=True, length:=20)>
    Public Readonly Property FTNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Base Product?" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Base Product?", ReadOnly:=True, length:=1)>
    Public Readonly Property ISMPART As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Base Product No." Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Base Product No.", length:=15)>
    Public Property MPARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Base Product Desc." Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Base Product Desc.", ReadOnly:=True, length:=48)>
    Public Readonly Property MPARTDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Preferred Vendor" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Preferred Vendor", length:=16)>
    Public Property SUPNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Vendor Name" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Vendor Name", ReadOnly:=True, length:=48)>
    Public Readonly Property SUPDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Size Chart Code" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Size Chart Code", length:=6)>
    Public Property SIZEBARCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Size Chart Name" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Size Chart Name", ReadOnly:=True, length:=20)>
    Public Readonly Property SIZEBARNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Attribute Set Code" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Attribute Set Code", length:=8)>
    Public Property UNSPSCCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Attribute Set Desc." Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Attribute Set Desc.", ReadOnly:=True, length:=56)>
    Public Readonly Property UNSPSCDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "List Price (Sales)" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("List Price (Sales)")>
    Public Property BASEPLPRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Currency" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Currency", length:=3)>
    Public Property BASEPLCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Wholesale Price" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Wholesale Price")>
    Public Property WSPLPRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Currency" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Currency", length:=3)>
    Public Property WSPLCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Last Price" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Last Price", ReadOnly:=True)>
    Public Readonly Property LASTPRICE As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Curr" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Curr", ReadOnly:=True, length:=3)>
    Public Readonly Property CODE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Date of Last Price" Value of LOGPART.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Date of Last Price", ReadOnly:=True)>
    Public Readonly Property CURDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Price Source" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Price Source", ReadOnly:=True, length:=10)>
    Public Readonly Property CFNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Std Cost" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Std Cost")>
    Public Property PRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Cost" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Cost", ReadOnly:=True)>
    Public Readonly Property COST As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Std Cost ({F.F})" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Std Cost ({F.F})")>
    Public Property SECONDPRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Cost ({F.F})" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Cost ({F.F})", ReadOnly:=True)>
    Public Readonly Property SECONDCOST As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Costing Date" Value of LOGPART.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Costing Date", ReadOnly:=True)>
    Public Readonly Property COSTDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Min. Price Currency" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Min. Price Currency", ReadOnly:=True, length:=3)>
    Public Readonly Property MINCODE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Minimum Price" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Minimum Price")>
    Public Property MINPRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Purchase Price" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Purchase Price")>
    Public Property PURPRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Commission Price" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Commission Price")>
    Public Property FOBPRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Currency" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Currency", length:=3)>
    Public Property PURCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Maximum Repair Price" Value of LOGPART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Maximum Repair Price")>
    Public Property MAXREPAIRPRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Curr" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Curr", length:=3)>
    Public Property REPAIRCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Number Template" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Number Template", length:=12)>
    Public Property PARTNAMEPATNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Last Sales Transact." Value of LOGPART.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Last Sales Transact.", ReadOnly:=True)>
    Public Readonly Property SALETRANSDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Last Purchase Trans." Value of LOGPART.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Last Purchase Trans.", ReadOnly:=True)>
    Public Readonly Property PURTRANSDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Last Warehouse Trans" Value of LOGPART.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Last Warehouse Trans", ReadOnly:=True)>
    Public Readonly Property WARHSTRANSDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Product Type-Distrib" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Product Type-Distrib", length:=3)>
    Public Property PARTTYPECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Prod Type-Distr Desc" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Prod Type-Distr Desc", ReadOnly:=True, length:=32)>
    Public Readonly Property PARTTYPEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Attachments?" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Attachments?", ReadOnly:=True, length:=1)>
    Public Readonly Property EXTFILEFLAG As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Signature" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Signature", ReadOnly:=True, length:=20)>
    Public Readonly Property USERLOGIN As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Time Stamp" Value of LOGPART.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Time Stamp", ReadOnly:=True)>
    Public Readonly Property UDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC1.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC1.F}", length:=48)>
    Public Property SPEC1 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC2.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC2.F}", length:=20)>
    Public Property SPEC2 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC3.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC3.F}", length:=20)>
    Public Property SPEC3 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC4.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC4.F}", length:=20)>
    Public Property SPEC4 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC5.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC5.F}", length:=20)>
    Public Property SPEC5 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC6.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC6.F}", length:=12)>
    Public Property SPEC6 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC7.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC7.F}", length:=12)>
    Public Property SPEC7 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC8.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC8.F}", length:=12)>
    Public Property SPEC8 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC9.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC9.F}", length:=12)>
    Public Property SPEC9 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC10.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC10.F}", length:=12)>
    Public Property SPEC10 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC11.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC11.F}", length:=12)>
    Public Property SPEC11 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC12.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC12.F}", length:=12)>
    Public Property SPEC12 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC13.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC13.F}", length:=12)>
    Public Property SPEC13 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC14.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC14.F}", length:=12)>
    Public Property SPEC14 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC15.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC15.F}", length:=12)>
    Public Property SPEC15 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC16.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC16.F}", length:=12)>
    Public Property SPEC16 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC17.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC17.F}", length:=12)>
    Public Property SPEC17 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC18.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC18.F}", length:=12)>
    Public Property SPEC18 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC19.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC19.F}", length:=12)>
    Public Property SPEC19 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC20.F}" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC20.F}", length:=12)>
    Public Property SPEC20 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Storefront Display" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Storefront Display", length:=1)>
    Public Property WEBLEVEL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Price Policy" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Price Policy", length:=2)>
    Public Property PRICEPOLICY As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Put Strategy Code" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Put Strategy Code", length:=8)>
    Public Property STORAGETYPECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Put Strategy Descrip" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Put Strategy Descrip", ReadOnly:=True, length:=32)>
    Public Readonly Property STORAGETYPEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Pick Order" Value of LOGPART.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Pick Order")>
    Public Property PIKORDER As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Pick by Crate" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Pick by Crate", length:=1)>
    Public Property PICKBYPACKS As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Subsidiary Code" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Subsidiary Code", length:=8)>
    Public Property COMPANYNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Subsidiary Name" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Subsidiary Name", ReadOnly:=True, length:=48)>
    Public Readonly Property COMPANYDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Work Item?" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Work Item?", length:=1)>
    Public Property WMSSERVFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Buyer" Value of LOGPART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Buyer", length:=20)>
    Public Property BUYERLOGIN As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Allowed Inv Age-Mos." Value of LOGPART.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Allowed Inv Age-Mos.")>
    Public Property DCMONTHS As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Inv Storage Age(Mos)" Value of LOGPART.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Inv Storage Age(Mos)")>
    Public Property PUTDCMONTHS As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Days Until Expirat'n" Value of LOGPART.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Days Until Expirat'n")>
    Public Property MINEXPDAYS As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part (ID)" Value of LOGPART.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Part (ID)")>
    Public Property EXTPART As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowLOGPART.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialLOGPART 

    Public Property PARTNAME As String
    Public Property BARCODE As String
    Public Property PARTDES As String
    Public Property EPARTDES As String
    Public Property STATDES As String
    Public Property TYPE As String
    Public Property INVFLAG As String
    Public Property NSFLAG As String
    Public Property SERNFLAG As String
    Public Property SHOWINWEB As String
    Public Property OWNERLOGIN As String
    Public Property CREATEDDATE As Date?
    Public Property PUNITNAME As String
    Public Property UNITNAME As String
    Public Property EXTFILENAME As String
    Public Property CONV As Decimal?
    Public Property NOTFIXEDCONV As String
    Public Property FAMILYNAME As String
    Public Property FAMILYDES As String
    Public Property FTCODE As String
    Public Property FTNAME As String
    Public Property ISMPART As String
    Public Property MPARTNAME As String
    Public Property MPARTDES As String
    Public Property SUPNAME As String
    Public Property SUPDES As String
    Public Property SIZEBARCODE As String
    Public Property SIZEBARNAME As String
    Public Property UNSPSCCODE As String
    Public Property UNSPSCDES As String
    Public Property BASEPLPRICE As Decimal?
    Public Property BASEPLCODE As String
    Public Property WSPLPRICE As Decimal?
    Public Property WSPLCODE As String
    Public Property LASTPRICE As Decimal?
    Public Property CODE As String
    Public Property CURDATE As Date?
    Public Property CFNAME As String
    Public Property PRICE As Decimal?
    Public Property COST As Decimal?
    Public Property SECONDPRICE As Decimal?
    Public Property SECONDCOST As Decimal?
    Public Property COSTDATE As Date?
    Public Property MINCODE As String
    Public Property MINPRICE As Decimal?
    Public Property PURPRICE As Decimal?
    Public Property FOBPRICE As Decimal?
    Public Property PURCODE As String
    Public Property MAXREPAIRPRICE As Decimal?
    Public Property REPAIRCODE As String
    Public Property PARTNAMEPATNAME As String
    Public Property SALETRANSDATE As Date?
    Public Property PURTRANSDATE As Date?
    Public Property WARHSTRANSDATE As Date?
    Public Property PARTTYPECODE As String
    Public Property PARTTYPEDES As String
    Public Property EXTFILEFLAG As String
    Public Property USERLOGIN As String
    Public Property UDATE As Date?
    Public Property SPEC1 As String
    Public Property SPEC2 As String
    Public Property SPEC3 As String
    Public Property SPEC4 As String
    Public Property SPEC5 As String
    Public Property SPEC6 As String
    Public Property SPEC7 As String
    Public Property SPEC8 As String
    Public Property SPEC9 As String
    Public Property SPEC10 As String
    Public Property SPEC11 As String
    Public Property SPEC12 As String
    Public Property SPEC13 As String
    Public Property SPEC14 As String
    Public Property SPEC15 As String
    Public Property SPEC16 As String
    Public Property SPEC17 As String
    Public Property SPEC18 As String
    Public Property SPEC19 As String
    Public Property SPEC20 As String
    Public Property WEBLEVEL As String
    Public Property PRICEPOLICY As String
    Public Property STORAGETYPECODE As String
    Public Property STORAGETYPEDES As String
    Public Property PIKORDER As Integer?
    Public Property PICKBYPACKS As String
    Public Property COMPANYNAME As String
    Public Property COMPANYDES As String
    Public Property WMSSERVFLAG As String
    Public Property BUYERLOGIN As String
    Public Property DCMONTHS As Integer?
    Public Property PUTDCMONTHS As Integer?
    Public Property MINEXPDAYS As Integer?
    Public Property EXTPART As Integer?


End Class