Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: ORDERITEMS as List(Of rowORDERITEMS)
''' Date: 20/03/2020
'''
''' </summary>
<oFormClass("rowORDERITEMS")>
Public Class ORDERITEMS : Inherits oForm

    ''' <summary>
    ''' ORDERITEMS Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the ORDERITEMS form.
    ''' </summary>
    ''' <returns>rowORDERITEMS</returns>
    Public Function AddRow() As rowORDERITEMS
        With Me
            .Add(New rowORDERITEMS(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the ORDERITEMS form.
''' </summary>
<oRowClass("ORDERITEMS", "serialORDERITEMS")>
Public Class rowORDERITEMS : Inherits oRow

    ''' <summary>
    ''' rowORDERITEMS Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Part Number" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Number", mandatory:=True, length:=15)>
    Public Property PARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Description" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Description", length:=48)>
    Public Property PDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Quantity" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Quantity")>
    Public Property TQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Unit" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Unit", ReadOnly:=True, length:=3)>
    Public Readonly Property TUNITNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Unit Price" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Unit Price")>
    Public Property PRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Cost" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Cost")>
    Public Property PURCHASEPRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Item Currency" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Item Currency", mandatory:=True, length:=3)>
    Public Property ICODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Due Date" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Due Date", mandatory:=True)>
    Public Property DUEDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Closed?" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Closed?", length:=1)>
    Public Property CLOSEDBOOL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Balance" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Balance", ReadOnly:=True)>
    Public Readonly Property TBALANCE As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Balance (Crates)" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Balance (Crates)", ReadOnly:=True)>
    Public Readonly Property PACKBALANCE As Integer
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Qty Packed/InternRep" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Qty Packed/InternRep", ReadOnly:=True)>
    Public Readonly Property PACKED As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Qty Packed (Crates)" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Qty Packed (Crates)", ReadOnly:=True)>
    Public Readonly Property PACKPACKED As Integer
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Discount%" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Discount%")>
    Public Property PERCENT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Unit Prc After Disc" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Unit Prc After Disc", ReadOnly:=True)>
    Public Readonly Property DISPRICE As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Extended Price" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Extended Price", ReadOnly:=True)>
    Public Readonly Property QPRICE As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Price Incl. Tax" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Price Incl. Tax")>
    Public Property VATPRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Profit" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Profit", ReadOnly:=True)>
    Public Readonly Property QPROFIT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Profit (%)" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Profit (%)", ReadOnly:=True)>
    Public Readonly Property QPROFITPERCENT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Value of Balance" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Value of Balance", ReadOnly:=True)>
    Public Readonly Property PRICEBAL As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Order Currency" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Order Currency", ReadOnly:=True, length:=3)>
    Public Readonly Property CODE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Price Source" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Price Source", ReadOnly:=True, length:=16)>
    Public Readonly Property PRSOURCENAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Cost Source" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Cost Source", ReadOnly:=True, length:=16)>
    Public Readonly Property PURSOURCENAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Packing Crates (No.)" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Packing Crates (No.)")>
    Public Property NUMPACK As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Crate Type Code" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Crate Type Code", length:=2)>
    Public Property PACKCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Product Bundle" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Product Bundle", ReadOnly:=True, length:=6)>
    Public Readonly Property MODELNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Planned Hrs/Unit" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Planned Hrs/Unit")>
    Public Property PLANHOURSD As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Total Planned Hours" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Total Planned Hours", ReadOnly:=True)>
    Public Readonly Property PLANHOURSSUM As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Part Revision No." Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Revision No.", length:=10)>
    Public Property REVNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Taxable?" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Taxable?", length:=1)>
    Public Property VATFLAGA As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Rep's Commission (%)" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Rep's Commission (%)")>
    Public Property COMMISSION As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Bar Code" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bar Code", length:=16)>
    Public Property BARCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Work Order/Lot" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Work Order/Lot", length:=22)>
    Public Property SERIALNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Cust. Part Number" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Cust. Part Number", length:=15)>
    Public Property CUSTPARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Customer Bar Code" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer Bar Code", length:=16)>
    Public Property CUSTPARTBARCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Cust's Order Ln" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Cust's Order Ln")>
    Public Property YOURORDLINE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Qty (Factory Units)" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Qty (Factory Units)", ReadOnly:=True)>
    Public Readonly Property QUANT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Balance (Fact. Unit)" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Balance (Fact. Unit)", ReadOnly:=True)>
    Public Readonly Property ABALANCE As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Planning Balance" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Planning Balance", ReadOnly:=True)>
    Public Readonly Property PBALANCE As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Factory Unit" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Factory Unit", ReadOnly:=True, length:=3)>
    Public Readonly Property UNITNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Attribute Set Code" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Attribute Set Code", length:=8)>
    Public Property UNSPSCCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Attribute Set Desc." Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Attribute Set Desc.", ReadOnly:=True, length:=56)>
    Public Readonly Property UNSPSCDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Prod. Planning Group" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Prod. Planning Group", length:=12)>
    Public Property CLUSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "MRP?" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("MRP?", length:=1)>
    Public Property MRP As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Planned End Date" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Planned End Date", ReadOnly:=True)>
    Public Readonly Property PDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Requested Date" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Requested Date")>
    Public Property PRDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Cash Flow Date" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Cash Flow Date")>
    Public Property CASHFLOWDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Site" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Site", length:=4)>
    Public Property DCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Site Description" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Site Description", ReadOnly:=True, length:=32)>
    Public Readonly Property CODEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Budget Item" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Budget Item", length:=24)>
    Public Property BUDCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Profit Centre" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Profit Centre", length:=8)>
    Public Property COSTCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Exchange Rate" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Exchange Rate")>
    Public Property EXCH As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Bonus Item?" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bonus Item?", ReadOnly:=True, length:=1)>
    Public Readonly Property PBONUSFLAG As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Status" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Status", length:=20)>
    Public Property ORDISTATUSDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Copy Preferred Vend" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Copy Preferred Vend", length:=1)>
    Public Property COPYFAVSUPFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Vendor (Purchasing)" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Vendor (Purchasing)", length:=16)>
    Public Property SUPNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Consider Credit?" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Consider Credit?", length:=1)>
    Public Property OBFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Prepaid?" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Prepaid?", length:=1)>
    Public Property PREPAYED As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Billing Customer" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Billing Customer", length:=16)>
    Public Property PAYCUSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Child Part Total?" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Child Part Total?", length:=1)>
    Public Property PARTTREEFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Customer Name" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer Name", ReadOnly:=True, length:=48)>
    Public Readonly Property PAYCUSTDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Linked Currency" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Linked Currency", length:=3)>
    Public Property LCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Base Rate" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Base Rate")>
    Public Property LEXCH As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Incl. in Proj. Cost?" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Incl. in Proj. Cost?", length:=1)>
    Public Property PROJCOSTFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Base Product No." Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Base Product No.", length:=15)>
    Public Property MPARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Base Product Desc." Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Base Product Desc.", ReadOnly:=True, length:=48)>
    Public Readonly Property MPARTDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Part by Base Product" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part by Base Product", length:=15)>
    Public Property MMPARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Remark" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Remark", length:=24)>
    Public Property REMARK1 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Remark 2" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Remark 2", length:=24)>
    Public Property REMARK2 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Kit Number" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Kit Number")>
    Public Property KITNUM As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Quality Code" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Quality Code", length:=4)>
    Public Property QRANKCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Quality Description" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Quality Description", ReadOnly:=True, length:=32)>
    Public Readonly Property QRANKDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Allowed Inv Age-Mos." Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Allowed Inv Age-Mos.")>
    Public Property DCMONTHS As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Days Until Expirat'n" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Days Until Expirat'n")>
    Public Property MINEXPDAYS As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Warehouse Remarks" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Warehouse Remarks", length:=24)>
    Public Property WARHSREMARK As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Blanket Order" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Blanket Order", length:=16)>
    Public Property DEALNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Line - Blanket Order" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Line - Blanket Order")>
    Public Property DLINE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Bill by Pulses?" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bill by Pulses?", ReadOnly:=True, length:=1)>
    Public Readonly Property CHARGEPULSES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Line Item (ID)" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Line Item (ID)")>
    Public Property ORDI As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Order (ID)" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Order (ID)", Key:=True)>
    Public Property CHARGEIV As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Key Line" Value of ORDERITEMS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Key Line", Key:=True)>
    Public Property KLINE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowORDERITEMS.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialORDERITEMS 

    Public Property PARTNAME As String
    Public Property PDES As String
    Public Property TQUANT As Decimal?
    Public Property TUNITNAME As String
    Public Property PRICE As Decimal?
    Public Property PURCHASEPRICE As Decimal?
    Public Property ICODE As String
    Public Property DUEDATE As Date?
    Public Property CLOSEDBOOL As String
    Public Property TBALANCE As Decimal?
    Public Property PACKBALANCE As Integer?
    Public Property PACKED As Decimal?
    Public Property PACKPACKED As Integer?
    Public Property PERCENT As Decimal?
    Public Property DISPRICE As Decimal?
    Public Property QPRICE As Decimal?
    Public Property VATPRICE As Decimal?
    Public Property QPROFIT As Decimal?
    Public Property QPROFITPERCENT As Decimal?
    Public Property PRICEBAL As Decimal?
    Public Property CODE As String
    Public Property PRSOURCENAME As String
    Public Property PURSOURCENAME As String
    Public Property NUMPACK As Integer?
    Public Property PACKCODE As String
    Public Property MODELNAME As String
    Public Property PLANHOURSD As Decimal?
    Public Property PLANHOURSSUM As Decimal?
    Public Property REVNAME As String
    Public Property VATFLAGA As String
    Public Property COMMISSION As Decimal?
    Public Property BARCODE As String
    Public Property SERIALNAME As String
    Public Property CUSTPARTNAME As String
    Public Property CUSTPARTBARCODE As String
    Public Property YOURORDLINE As Integer?
    Public Property QUANT As Decimal?
    Public Property ABALANCE As Decimal?
    Public Property PBALANCE As Decimal?
    Public Property UNITNAME As String
    Public Property UNSPSCCODE As String
    Public Property UNSPSCDES As String
    Public Property CLUSTNAME As String
    Public Property MRP As String
    Public Property PDATE As Date?
    Public Property PRDATE As Date?
    Public Property CASHFLOWDATE As Date?
    Public Property DCODE As String
    Public Property CODEDES As String
    Public Property BUDCODE As String
    Public Property COSTCNAME As String
    Public Property EXCH As Decimal?
    Public Property PBONUSFLAG As String
    Public Property ORDISTATUSDES As String
    Public Property COPYFAVSUPFLAG As String
    Public Property SUPNAME As String
    Public Property OBFLAG As String
    Public Property PREPAYED As String
    Public Property PAYCUSTNAME As String
    Public Property PARTTREEFLAG As String
    Public Property PAYCUSTDES As String
    Public Property LCODE As String
    Public Property LEXCH As Decimal?
    Public Property PROJCOSTFLAG As String
    Public Property MPARTNAME As String
    Public Property MPARTDES As String
    Public Property MMPARTNAME As String
    Public Property REMARK1 As String
    Public Property REMARK2 As String
    Public Property KITNUM As Integer?
    Public Property QRANKCODE As String
    Public Property QRANKDES As String
    Public Property DCMONTHS As Integer?
    Public Property MINEXPDAYS As Integer?
    Public Property WARHSREMARK As String
    Public Property DEALNAME As String
    Public Property DLINE As Integer?
    Public Property CHARGEPULSES As String
    Public Property ORDI As Integer?
    Public Property CHARGEIV As Integer?
    Public Property KLINE As Integer?


End Class