Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: ORDERS as List(Of rowORDERS)
''' Date: 21/01/2020
'''
''' </summary>
<oFormClass("rowORDERS", "ORDERITEMS", "SHIPTO2")>
Public Class ORDERS : Inherits oForm

    ''' <summary>
    ''' ORDERS Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the ORDERS form.
    ''' </summary>
    ''' <returns>rowORDERS</returns>
    Public Function AddRow() As rowORDERS
        With Me
            .Add(New rowORDERS(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the ORDERS form.
''' </summary>
<oRowClass("ORDERS", "serialORDERS")>
Public Class rowORDERS : Inherits oRow

    ''' <summary>
    ''' rowORDERS Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get/set the ORDERITEMS subform.
    ''' </summary>
    ''' <returns>ORDERITEMS</returns>
	Public Property ORDERITEMS As ORDERITEMS
        Get
            Return MyBase.SubForms("ORDERITEMS")
        End Get
        Set(value As ORDERITEMS)
            MyBase.SubForms("ORDERITEMS") = value
        End Set
    End Property    
	''' <summary>
    ''' Get/set the SHIPTO2 subform.
    ''' </summary>
    ''' <returns>SHIPTO2</returns>
	Public Property SHIPTO2 As SHIPTO2
        Get
            Return MyBase.SubForms("SHIPTO2")
        End Get
        Set(value As SHIPTO2)
            MyBase.SubForms("SHIPTO2") = value
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Customer Number" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer Number", mandatory:=True, length:=16)>
    Public Property CUSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Customer Name" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer Name", length:=48)>
    Public Property CDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Contact" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Contact", length:=37)>
    Public Property NAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Job Title" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Job Title", ReadOnly:=True, length:=32)>
    Public Readonly Property POSITIONDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Date" Value of ORDERS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Date", mandatory:=True)>
    Public Property CURDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Order" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Order", Key:=True, length:=16)>
    Public Property ORDNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sales Rep Order Num" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales Rep Order Num", length:=16)>
    Public Property BOOKNUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Project Number" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Project Number", length:=16)>
    Public Property DOCNO As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Project Description" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Project Description", ReadOnly:=True, length:=32)>
    Public Readonly Property PROJDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Order Status" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Order Status", mandatory:=True, length:=12)>
    Public Property ORDSTATUSDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Closed" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Closed", length:=1)>
    Public Property BOOLCLOSED As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Partially Closed" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Partially Closed", ReadOnly:=True, length:=1)>
    Public Readonly Property BOOLPCLOSED As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Forecast/Stock Order" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Forecast/Stock Order", length:=1)>
    Public Property FORECASTFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Price Quotation" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Price Quotation", length:=16)>
    Public Property CPROFNUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Price List" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Price List", length:=6)>
    Public Property PLNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Blanket Order" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Blanket Order", length:=16)>
    Public Property DEALNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Cust's Blanket Order" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Cust's Blanket Order", ReadOnly:=True, length:=32)>
    Public Readonly Property YOURDEALNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Details" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Details", length:=24)>
    Public Property DETAILS As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Status Update Date" Value of ORDERS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Status Update Date", ReadOnly:=True)>
    Public Readonly Property STATUSDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "RMA Number" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("RMA Number", length:=16)>
    Public Property RMADOCNUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Due Date" Value of ORDERS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Due Date")>
    Public Property DUEDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sales Rep Number" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales Rep Number", length:=16)>
    Public Property AGENTCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Sales Rep Name" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales Rep Name", ReadOnly:=True, length:=6)>
    Public Readonly Property AGENTNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Branch" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Branch", length:=6)>
    Public Property BRANCHNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Site" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Site", length:=4)>
    Public Property DCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Site Description" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Site Description", ReadOnly:=True, length:=32)>
    Public Readonly Property CODEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Shipment Code" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Shipment Code", length:=2)>
    Public Property STCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Shipping Method" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Shipping Method", ReadOnly:=True, length:=6)>
    Public Readonly Property STDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Type of Sale" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Type of Sale", length:=3)>
    Public Property TYPECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Type of Sale-Descrip" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Type of Sale-Descrip", ReadOnly:=True, length:=12)>
    Public Readonly Property TYPEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Customer's Purch Ord" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer's Purch Ord", length:=15)>
    Public Property REFERENCE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Product Bundle" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Product Bundle", length:=6)>
    Public Property MODELNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Quantity" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Quantity")>
    Public Property QUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Price Bef. Disc." Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Price Bef. Disc.", ReadOnly:=True)>
    Public Readonly Property QPRICE As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "% Overall Discount" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("% Overall Discount")>
    Public Property PERCENT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Price After Discount" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Price After Discount", ReadOnly:=True)>
    Public Readonly Property DISPRICE As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Sales Tax" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Sales Tax", ReadOnly:=True)>
    Public Readonly Property VAT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Tax Code" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Tax Code", mandatory:=True, length:=8)>
    Public Property TAXCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Final Price" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Final Price")>
    Public Property TOTPRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Curr" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Curr", mandatory:=True, length:=3)>
    Public Property CODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Cost" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Cost", ReadOnly:=True)>
    Public Readonly Property TOTPURCHASEPRICE As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Profit" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Profit", ReadOnly:=True)>
    Public Readonly Property QPROFIT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Profit (%)" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Profit (%)", ReadOnly:=True)>
    Public Readonly Property PROFITPERCENT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Linked Currency" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Linked Currency", length:=3)>
    Public Property LCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Base Rate" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Base Rate")>
    Public Property LEXCH As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Minimum Linkage %" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Minimum Linkage %")>
    Public Property LEXCHTOL As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Negative Linkage?" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Negative Linkage?", length:=1)>
    Public Property LEXCHNEG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Price Linkage" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Price Linkage", length:=1)>
    Public Property ADJPRICEFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Linkage Method" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Linkage Method", ReadOnly:=True, length:=32)>
    Public Readonly Property ADJPRICEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Linkage Options" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Linkage Options", length:=1)>
    Public Property LINKOPTIONS As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Payment Terms Code" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Payment Terms Code", length:=3)>
    Public Property PAYCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Payment Terms" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Payment Terms", ReadOnly:=True, length:=24)>
    Public Readonly Property PAYDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Consider Credit?" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Consider Credit?", length:=1)>
    Public Property OBFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "AdvancePaymt Balance" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("AdvancePaymt Balance", ReadOnly:=True)>
    Public Readonly Property ADVBAL As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "% Advance Pay Deduct" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("% Advance Pay Deduct")>
    Public Property ADVPERCENT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "VAT Number-Cust." Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("VAT Number-Cust.", length:=16)>
    Public Property ORDREFA As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Assigned to" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Assigned to", mandatory:=True, length:=20)>
    Public Property DOERNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Employee 2" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Employee 2", length:=20)>
    Public Property DOERNAME2 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Employee 3" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Employee 3", length:=20)>
    Public Property DOERNAME3 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Start Date" Value of ORDERS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Start Date")>
    Public Property SDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Day" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Day", ReadOnly:=True, length:=3)>
    Public Readonly Property DAY As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Start Time" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Start Time", length:=5)>
    Public Property STIME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "End Date" Value of ORDERS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("End Date")>
    Public Property EDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Day" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Day", ReadOnly:=True, length:=3)>
    Public Readonly Property EDAY As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "End Time" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("End Time", length:=5)>
    Public Property ETIME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sending Warehouse" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sending Warehouse", length:=4)>
    Public Property WARHSNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Bin" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bin", length:=14)>
    Public Property LOCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Warehouse Descrip." Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Warehouse Descrip.", ReadOnly:=True, length:=32)>
    Public Readonly Property WARHSDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "For Consignmt Warehs" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("For Consignmt Warehs", length:=4)>
    Public Property TOWARHSNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Bin (Consignment)" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bin (Consignment)", length:=14)>
    Public Property TOLOCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Ware Desc-Consignmt" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Ware Desc-Consignmt", ReadOnly:=True, length:=32)>
    Public Readonly Property TOWARHSDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Attachments?" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Attachments?", ReadOnly:=True, length:=1)>
    Public Readonly Property EXTFILEFLAG As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Ignore Bonuses?" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Ignore Bonuses?", length:=1)>
    Public Property BONUSFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Sales Oppor. Number" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Sales Oppor. Number", length:=24)>
    Public Property CCNUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Territory Code" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Territory Code", ReadOnly:=True, length:=12)>
    Public Readonly Property TERRITORYCODE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Territory Name" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Territory Name", ReadOnly:=True, length:=32)>
    Public Readonly Property TERRITORYDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Qty of Items" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Qty of Items", ReadOnly:=True)>
    Public Readonly Property TOTQUANT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Separate Pick?" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Separate Pick?", length:=1)>
    Public Property PIKALONEFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Storage Zone" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Storage Zone", length:=2)>
    Public Property STZONECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Distrib. Route Code" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Distrib. Route Code", length:=3)>
    Public Property DISTRLINECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Distrib. Route Desc." Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Distrib. Route Desc.", ReadOnly:=True, length:=12)>
    Public Readonly Property DISTRLINEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Zone Description" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Zone Description", ReadOnly:=True, length:=32)>
    Public Readonly Property STZONEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Target Doc-WarhsTask" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Target Doc-WarhsTask", length:=4)>
    Public Property WTASKDOCCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Target Doc. Desc." Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Target Doc. Desc.", ReadOnly:=True, length:=16)>
    Public Readonly Property WTASKDOCDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Address for Invoice" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Address for Invoice", length:=4)>
    Public Property IVDCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Address for Inv-Desc" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Address for Inv-Desc", ReadOnly:=True, length:=32)>
    Public Readonly Property IVDCODEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Link as of Date" Value of ORDERS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Link as of Date")>
    Public Property LFROMDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Date of Base Rate" Value of ORDERS.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Date of Base Rate")>
    Public Property LBASEDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "% of Linkage" Value of ORDERS.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("% of Linkage")>
    Public Property LPERCENT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Shipper Instructions" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Shipper Instructions", length:=32)>
    Public Property SHIPREMARK As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Latitude" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Latitude", length:=20)>
    Public Property GPSX As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Longitude" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Longitude", length:=20)>
    Public Property GPSY As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Pick Order" Value of ORDERS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Pick Order")>
    Public Property PIKORDER As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Print Part Attachmts" Value of ORDERS.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Print Part Attachmts", length:=1)>
    Public Property INCPARTEXT As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Order (ID)" Value of ORDERS.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Order (ID)")>
    Public Property FOLLOWUPIV As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowORDERS.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialORDERS 

    Public Property CUSTNAME As String
    Public Property CDES As String
    Public Property NAME As String
    Public Property POSITIONDES As String
    Public Property CURDATE As Date?
    Public Property ORDNAME As String
    Public Property BOOKNUM As String
    Public Property DOCNO As String
    Public Property PROJDES As String
    Public Property ORDSTATUSDES As String
    Public Property BOOLCLOSED As String
    Public Property BOOLPCLOSED As String
    Public Property FORECASTFLAG As String
    Public Property CPROFNUM As String
    Public Property PLNAME As String
    Public Property DEALNAME As String
    Public Property YOURDEALNAME As String
    Public Property DETAILS As String
    Public Property STATUSDATE As Date?
    Public Property RMADOCNUM As String
    Public Property DUEDATE As Date?
    Public Property AGENTCODE As String
    Public Property AGENTNAME As String
    Public Property BRANCHNAME As String
    Public Property DCODE As String
    Public Property CODEDES As String
    Public Property STCODE As String
    Public Property STDES As String
    Public Property TYPECODE As String
    Public Property TYPEDES As String
    Public Property REFERENCE As String
    Public Property MODELNAME As String
    Public Property QUANT As Decimal?
    Public Property QPRICE As Decimal?
    Public Property PERCENT As Decimal?
    Public Property DISPRICE As Decimal?
    Public Property VAT As Decimal?
    Public Property TAXCODE As String
    Public Property TOTPRICE As Decimal?
    Public Property CODE As String
    Public Property TOTPURCHASEPRICE As Decimal?
    Public Property QPROFIT As Decimal?
    Public Property PROFITPERCENT As Decimal?
    Public Property LCODE As String
    Public Property LEXCH As Decimal?
    Public Property LEXCHTOL As Decimal?
    Public Property LEXCHNEG As String
    Public Property ADJPRICEFLAG As String
    Public Property ADJPRICEDES As String
    Public Property LINKOPTIONS As String
    Public Property PAYCODE As String
    Public Property PAYDES As String
    Public Property OBFLAG As String
    Public Property ADVBAL As Decimal?
    Public Property ADVPERCENT As Decimal?
    Public Property ORDREFA As String
    Public Property DOERNAME As String
    Public Property DOERNAME2 As String
    Public Property DOERNAME3 As String
    Public Property SDATE As Date?
    Public Property DAY As String
    Public Property STIME As String
    Public Property EDATE As Date?
    Public Property EDAY As String
    Public Property ETIME As String
    Public Property WARHSNAME As String
    Public Property LOCNAME As String
    Public Property WARHSDES As String
    Public Property TOWARHSNAME As String
    Public Property TOLOCNAME As String
    Public Property TOWARHSDES As String
    Public Property EXTFILEFLAG As String
    Public Property BONUSFLAG As String
    Public Property CCNUM As String
    Public Property TERRITORYCODE As String
    Public Property TERRITORYDES As String
    Public Property TOTQUANT As Decimal?
    Public Property PIKALONEFLAG As String
    Public Property STZONECODE As String
    Public Property DISTRLINECODE As String
    Public Property DISTRLINEDES As String
    Public Property STZONEDES As String
    Public Property WTASKDOCCODE As String
    Public Property WTASKDOCDES As String
    Public Property IVDCODE As String
    Public Property IVDCODEDES As String
    Public Property LFROMDATE As Date?
    Public Property LBASEDATE As Date?
    Public Property LPERCENT As Decimal?
    Public Property SHIPREMARK As String
    Public Property GPSX As String
    Public Property GPSY As String
    Public Property PIKORDER As Integer?
    Public Property INCPARTEXT As String
    Public Property FOLLOWUPIV As Integer?


End Class