Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: PARTARC as List(Of rowPARTARC)
''' Date: 20/03/2020
'''
''' </summary>
<oFormClass("rowPARTARC")>
Public Class PARTARC : Inherits oForm

    ''' <summary>
    ''' PARTARC Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the PARTARC form.
    ''' </summary>
    ''' <returns>rowPARTARC</returns>
    Public Function AddRow() As rowPARTARC
        With Me
            .Add(New rowPARTARC(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the PARTARC form.
''' </summary>
<oRowClass("PARTARC", "serialPARTARC")>
Public Class rowPARTARC : Inherits oRow

    ''' <summary>
    ''' rowPARTARC Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Child Part Number" Value of PARTARC.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Child Part Number", mandatory:=True, length:=15)>
    Public Property SONNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Type (P/R)" Value of PARTARC.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Type (P/R)", ReadOnly:=True, length:=1)>
    Public Readonly Property TYPE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Part Description" Value of PARTARC.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Description", ReadOnly:=True, length:=48)>
    Public Readonly Property SONDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Child Part Revision" Value of PARTARC.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Child Part Revision", length:=10)>
    Public Property SONREVNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Qty(Child)" Value of PARTARC.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Qty(Child)", mandatory:=True)>
    Public Property SONQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Factory Unit" Value of PARTARC.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Factory Unit", ReadOnly:=True, length:=3)>
    Public Readonly Property UNITNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Coefficient" Value of PARTARC.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Coefficient", ReadOnly:=True)>
    Public Readonly Property COEF As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Operand (C/M/D)" Value of PARTARC.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Operand (C/M/D)", mandatory:=True, length:=1)>
    Public Property OP As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Variable" Value of PARTARC.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Variable", length:=16)>
    Public Property VARNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Scrap (%)" Value of PARTARC.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Scrap (%)")>
    Public Property SCRAP As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Parent Operation" Value of PARTARC.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Parent Operation", mandatory:=True, length:=16)>
    Public Property ACTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Child Operation" Value of PARTARC.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Child Operation", mandatory:=True, length:=16)>
    Public Property SONACTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Info Only" Value of PARTARC.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Info Only", length:=1)>
    Public Property INFOONLY As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Signature" Value of PARTARC.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Signature", ReadOnly:=True, length:=20)>
    Public Readonly Property USERLOGIN As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Time Stamp" Value of PARTARC.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Time Stamp", ReadOnly:=True)>
    Public Readonly Property UDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Effect Date-Revision" Value of PARTARC.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Effect Date-Revision", Key:=True)>
    Public Property RVFROMDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Operation (ID)" Value of PARTARC.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Operation (ID)", Key:=True)>
    Public Property ACT As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Child Part No. (ID)" Value of PARTARC.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Child Part No. (ID)", Key:=True)>
    Public Property SON As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Child Operation (ID)" Value of PARTARC.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Child Operation (ID)", Key:=True)>
    Public Property SONACT As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowPARTARC.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialPARTARC 

    Public Property SONNAME As String
    Public Property TYPE As String
    Public Property SONDES As String
    Public Property SONREVNAME As String
    Public Property SONQUANT As Decimal?
    Public Property UNITNAME As String
    Public Property COEF As Decimal?
    Public Property OP As String
    Public Property VARNAME As String
    Public Property SCRAP As Decimal?
    Public Property ACTNAME As String
    Public Property SONACTNAME As String
    Public Property INFOONLY As String
    Public Property USERLOGIN As String
    Public Property UDATE As Date?
    Public Property RVFROMDATE As Date?
    Public Property ACT As Integer?
    Public Property SON As Integer?
    Public Property SONACT As Integer?


End Class