Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: PART as List(Of rowPART)
''' Date: 20/03/2020
'''
''' </summary>
<oFormClass("rowPART", "PARTARC", "PARTREV", "REVISIONS")>
Public Class PART : Inherits oForm

    ''' <summary>
    ''' PART Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the PART form.
    ''' </summary>
    ''' <returns>rowPART</returns>
    Public Function AddRow() As rowPART
        With Me
            .Add(New rowPART(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the PART form.
''' </summary>
<oRowClass("PART", "serialPART")>
Public Class rowPART : Inherits oRow

    ''' <summary>
    ''' rowPART Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get/set the PARTARC subform.
    ''' </summary>
    ''' <returns>PARTARC</returns>
	Public Property PARTARC As PARTARC
        Get
            Return MyBase.SubForms("PARTARC")
        End Get
        Set(value As PARTARC)
            MyBase.SubForms("PARTARC") = value
        End Set
    End Property    
	''' <summary>
    ''' Get/set the PARTREV subform.
    ''' </summary>
    ''' <returns>PARTREV</returns>
	Public Property PARTREV As PARTREV
        Get
            Return MyBase.SubForms("PARTREV")
        End Get
        Set(value As PARTREV)
            MyBase.SubForms("PARTREV") = value
        End Set
    End Property    
	''' <summary>
    ''' Get/set the REVISIONS subform.
    ''' </summary>
    ''' <returns>REVISIONS</returns>
	Public Property REVISIONS As REVISIONS
        Get
            Return MyBase.SubForms("REVISIONS")
        End Get
        Set(value As REVISIONS)
            MyBase.SubForms("REVISIONS") = value
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Number" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Number", Key:=True, mandatory:=True, length:=15)>
    Public Property PARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Type (P/R/O)" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Type (P/R/O)", mandatory:=True, length:=1)>
    Public Property TYPE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Description" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Description", mandatory:=True, length:=48)>
    Public Property PARTDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Desc. (Lang 2)" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Desc. (Lang 2)", length:=48)>
    Public Property EPARTDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Routing" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Routing", length:=6)>
    Public Property PROCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Routing Description" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Routing Description", ReadOnly:=True, length:=32)>
    Public Readonly Property PROCDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Status" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Status", mandatory:=True, length:=12)>
    Public Property STATDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Assigned to" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Assigned to", mandatory:=True, length:=20)>
    Public Property OWNERLOGIN As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Buy/Sell Unit" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Buy/Sell Unit", mandatory:=True, length:=3)>
    Public Property PUNITNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Factory Unit" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Factory Unit", mandatory:=True, length:=3)>
    Public Property UNITNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Conversion Ratio" Value of PART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Conversion Ratio", mandatory:=True)>
    Public Property CONV As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Qty(Parent)" Value of PART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Qty(Parent)", mandatory:=True)>
    Public Property FATQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Revision No." Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Revision No.", length:=10)>
    Public Property REVNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Family" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Family", mandatory:=True, length:=8)>
    Public Property FAMILYNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "BOM Revisions?" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("BOM Revisions?", length:=1)>
    Public Property REVFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Preferred Status" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Preferred Status", length:=1)>
    Public Property PREFERRED As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Excess Inv. B/N/C/I" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Excess Inv. B/N/C/I", length:=1)>
    Public Property EXCESS As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Date Opened" Value of PART.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Date Opened", ReadOnly:=True)>
    Public Readonly Property CREATEDDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Issued to Kits?" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Issued to Kits?", length:=1)>
    Public Property KITFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Manual Issue?" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Manual Issue?", length:=1)>
    Public Property TAKEFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Maintain Serial Nos?" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Maintain Serial Nos?", length:=1)>
    Public Property SERNFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Scrap" Value of PART.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Scrap")>
    Public Property SCRAP As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Bar Code" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bar Code", length:=16)>
    Public Property BARCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Pallet Type Code" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Pallet Type Code", length:=3)>
    Public Property PALLETTYPECODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Pallet Type Desc." Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Pallet Type Desc.", ReadOnly:=True, length:=32)>
    Public Readonly Property PALLETTYPEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Main Byproduct Part#" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Main Byproduct Part#", length:=15)>
    Public Property MOLDPARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Main Byproduct Desc." Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Main Byproduct Desc.", ReadOnly:=True, length:=48)>
    Public Readonly Property MOLDPARTDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Variable Conversion" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Variable Conversion", length:=1)>
    Public Property NOTFIXEDCONV As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Designation Control?" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Designation Control?", length:=1)>
    Public Property LOCFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Attachments?" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Attachments?", ReadOnly:=True, length:=1)>
    Public Readonly Property EXTFILEFLAG As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC1.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC1.F}", length:=48)>
    Public Property SPEC1 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC2.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC2.F}", length:=20)>
    Public Property SPEC2 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC3.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC3.F}", length:=20)>
    Public Property SPEC3 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC4.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC4.F}", length:=20)>
    Public Property SPEC4 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC5.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC5.F}", length:=20)>
    Public Property SPEC5 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC6.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC6.F}", length:=12)>
    Public Property SPEC6 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC7.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC7.F}", length:=12)>
    Public Property SPEC7 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC8.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC8.F}", length:=12)>
    Public Property SPEC8 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC9.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC9.F}", length:=12)>
    Public Property SPEC9 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC10.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC10.F}", length:=12)>
    Public Property SPEC10 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC11.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC11.F}", length:=12)>
    Public Property SPEC11 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC12.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC12.F}", length:=12)>
    Public Property SPEC12 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC13.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC13.F}", length:=12)>
    Public Property SPEC13 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC14.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC14.F}", length:=12)>
    Public Property SPEC14 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC15.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC15.F}", length:=12)>
    Public Property SPEC15 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC16.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC16.F}", length:=12)>
    Public Property SPEC16 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC17.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC17.F}", length:=12)>
    Public Property SPEC17 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC18.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC18.F}", length:=12)>
    Public Property SPEC18 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC19.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC19.F}", length:=12)>
    Public Property SPEC19 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "{PARTSPEC_SPEC20.F}" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("{PARTSPEC_SPEC20.F}", length:=12)>
    Public Property SPEC20 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Storefront Display" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Storefront Display", length:=1)>
    Public Property WEBLEVEL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Signature" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Signature", ReadOnly:=True, length:=20)>
    Public Readonly Property USERLOGIN As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Time Stamp" Value of PART.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Time Stamp", ReadOnly:=True)>
    Public Readonly Property UDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Turnkey" Value of PART.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Turnkey", length:=1)>
    Public Property TURNKEY As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part (ID)" Value of PART.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Part (ID)")>
    Public Property NSCUST As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowPART.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialPART 

    Public Property PARTNAME As String
    Public Property TYPE As String
    Public Property PARTDES As String
    Public Property EPARTDES As String
    Public Property PROCNAME As String
    Public Property PROCDES As String
    Public Property STATDES As String
    Public Property OWNERLOGIN As String
    Public Property PUNITNAME As String
    Public Property UNITNAME As String
    Public Property CONV As Decimal?
    Public Property FATQUANT As Decimal?
    Public Property REVNAME As String
    Public Property FAMILYNAME As String
    Public Property REVFLAG As String
    Public Property PREFERRED As String
    Public Property EXCESS As String
    Public Property CREATEDDATE As Date?
    Public Property KITFLAG As String
    Public Property TAKEFLAG As String
    Public Property SERNFLAG As String
    Public Property SCRAP As Decimal?
    Public Property BARCODE As String
    Public Property PALLETTYPECODE As String
    Public Property PALLETTYPEDES As String
    Public Property MOLDPARTNAME As String
    Public Property MOLDPARTDES As String
    Public Property NOTFIXEDCONV As String
    Public Property LOCFLAG As String
    Public Property EXTFILEFLAG As String
    Public Property SPEC1 As String
    Public Property SPEC2 As String
    Public Property SPEC3 As String
    Public Property SPEC4 As String
    Public Property SPEC5 As String
    Public Property SPEC6 As String
    Public Property SPEC7 As String
    Public Property SPEC8 As String
    Public Property SPEC9 As String
    Public Property SPEC10 As String
    Public Property SPEC11 As String
    Public Property SPEC12 As String
    Public Property SPEC13 As String
    Public Property SPEC14 As String
    Public Property SPEC15 As String
    Public Property SPEC16 As String
    Public Property SPEC17 As String
    Public Property SPEC18 As String
    Public Property SPEC19 As String
    Public Property SPEC20 As String
    Public Property WEBLEVEL As String
    Public Property USERLOGIN As String
    Public Property UDATE As Date?
    Public Property TURNKEY As String
    Public Property NSCUST As Integer?


End Class