Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: PARTREV as List(Of rowPARTREV)
''' Date: 20/03/2020
'''
''' </summary>
<oFormClass("rowPARTREV")>
Public Class PARTREV : Inherits oForm

    ''' <summary>
    ''' PARTREV Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the PARTREV form.
    ''' </summary>
    ''' <returns>rowPARTREV</returns>
    Public Function AddRow() As rowPARTREV
        With Me
            .Add(New rowPARTREV(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the PARTREV form.
''' </summary>
<oRowClass("PARTREV", "serialPARTREV")>
Public Class rowPARTREV : Inherits oRow

    ''' <summary>
    ''' rowPARTREV Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Part Revision No." Value of PARTREV.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Revision No.", mandatory:=True, length:=10)>
    Public Property REVNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Use From" Value of PARTREV.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Use From")>
    Public Property FROMDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Next Signature" Value of PARTREV.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Next Signature", ReadOnly:=True, length:=20)>
    Public Readonly Property SIGNUSERLOGIN As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Authorized" Value of PARTREV.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Authorized", ReadOnly:=True, length:=1)>
    Public Readonly Property CONFIRMED As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "In Effect?" Value of PARTREV.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("In Effect?", length:=1)>
    Public Property VALID As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Not in Use" Value of PARTREV.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Not in Use", length:=1)>
    Public Property INACTIVE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "ECO Number" Value of PARTREV.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("ECO Number", length:=16)>
    Public Property ECONUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Signature" Value of PARTREV.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Signature", ReadOnly:=True, length:=20)>
    Public Readonly Property USERLOGIN As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Time Stamp" Value of PARTREV.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Time Stamp", ReadOnly:=True)>
    Public Readonly Property UDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Revision (ID)" Value of PARTREV.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Revision (ID)", Key:=True)>
    Public Property REV As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowPARTREV.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialPARTREV 

    Public Property REVNAME As String
    Public Property FROMDATE As Date?
    Public Property SIGNUSERLOGIN As String
    Public Property CONFIRMED As String
    Public Property VALID As String
    Public Property INACTIVE As String
    Public Property ECONUM As String
    Public Property USERLOGIN As String
    Public Property UDATE As Date?
    Public Property REV As Integer?


End Class