Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: SHIPTO2 as List(Of rowSHIPTO2)
''' Date: 21/01/2020
'''
''' </summary>
<oFormClass("rowSHIPTO2")>
Public Class SHIPTO2 : Inherits oForm

    ''' <summary>
    ''' SHIPTO2 Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the SHIPTO2 form.
    ''' </summary>
    ''' <returns>rowSHIPTO2</returns>
    Public Function AddRow() As rowSHIPTO2
        With Me
            .Add(New rowSHIPTO2(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the SHIPTO2 form.
''' </summary>
<oRowClass("SHIPTO2", "serialSHIPTO2")>
Public Class rowSHIPTO2 : Inherits oRow

    ''' <summary>
    ''' rowSHIPTO2 Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Name" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Name", length:=48)>
    Public Property CUSTDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Contact" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Contact", length:=37)>
    Public Property NAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Phone Number" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Phone Number", length:=20)>
    Public Property PHONENUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Fax Number" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Fax Number", length:=20)>
    Public Property FAX As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Street Address" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Street Address", length:=80)>
    Public Property ADDRESS As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Address (Line 2)" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Address (Line 2)", length:=80)>
    Public Property ADDRESS2 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Address (Line 3)" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Address (Line 3)", length:=80)>
    Public Property ADDRESS3 As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "City" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("City", length:=40)>
    Public Property STATE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "State" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("State", length:=40)>
    Public Property STATENAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Zip Code" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Zip Code", length:=10)>
    Public Property ZIP As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Country" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Country", length:=18)>
    Public Property COUNTRYNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Name (Lang 2)" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Name (Lang 2)", length:=48)>
    Public Property CUSTDESA As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Contact (Lang 2)" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Contact (Lang 2)", length:=24)>
    Public Property NAMEA As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Address (Lang 2)" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Address (Lang 2)", length:=80)>
    Public Property ADDRESSA As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "City (Lang 2)" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("City (Lang 2)", length:=40)>
    Public Property STATEA As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Tax Code" Value of SHIPTO2.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Tax Code", length:=8)>
    Public Property TAXCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowSHIPTO2.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialSHIPTO2 

    Public Property CUSTDES As String
    Public Property NAME As String
    Public Property PHONENUM As String
    Public Property FAX As String
    Public Property ADDRESS As String
    Public Property ADDRESS2 As String
    Public Property ADDRESS3 As String
    Public Property STATE As String
    Public Property STATENAME As String
    Public Property ZIP As String
    Public Property COUNTRYNAME As String
    Public Property CUSTDESA As String
    Public Property NAMEA As String
    Public Property ADDRESSA As String
    Public Property STATEA As String
    Public Property TAXCODE As String


End Class