Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: TRANSORDER_A as List(Of rowTRANSORDER_A)
''' Date: 21/01/2020
'''
''' </summary>
<oFormClass("rowTRANSORDER_A")>
Public Class TRANSORDER_A : Inherits oForm

    ''' <summary>
    ''' TRANSORDER_A Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the TRANSORDER_A form.
    ''' </summary>
    ''' <returns>rowTRANSORDER_A</returns>
    Public Function AddRow() As rowTRANSORDER_A
        With Me
            .Add(New rowTRANSORDER_A(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the TRANSORDER_A form.
''' </summary>
<oRowClass("TRANSORDER_A", "serialTRANSORDER_A")>
Public Class rowTRANSORDER_A : Inherits oRow

    ''' <summary>
    ''' rowTRANSORDER_A Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Part Number" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Number", mandatory:=True, length:=15)>
    Public Property PARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Description" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Description", length:=48)>
    Public Property PDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Work Order" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Work Order", mandatory:=True, length:=22)>
    Public Property SERIALNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Work Order Descrip." Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Work Order Descrip.", ReadOnly:=True, length:=48)>
    Public Readonly Property SERIALDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Bar Code" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bar Code", length:=16)>
    Public Property BARCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Revision No." Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Revision No.", length:=10)>
    Public Property REVNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "BOM Revision Number" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("BOM Revision Number", ReadOnly:=True, length:=3)>
    Public Readonly Property REVNUM As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Cust. Part Number" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Cust. Part Number", length:=15)>
    Public Property CUSTPARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Customer Bar Code" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer Bar Code", length:=16)>
    Public Property CUSTPARTBARCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Balance to Pack" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Balance to Pack")>
    Public Property CQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Warehouse Balance" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Warehouse Balance", ReadOnly:=True)>
    Public Readonly Property PQUANT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Approve" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Approve", length:=1)>
    Public Property SETFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Quantity" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Quantity")>
    Public Property TQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Unit" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Unit", ReadOnly:=True, length:=3)>
    Public Readonly Property TUNITNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Qty (Factory Units)" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Qty (Factory Units)")>
    Public Property QUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Factory Unit" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Factory Unit", ReadOnly:=True, length:=3)>
    Public Readonly Property UNITNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Crate Type Code" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Crate Type Code", length:=2)>
    Public Property PACKCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Crate Type Desc." Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Crate Type Desc.", ReadOnly:=True, length:=8)>
    Public Readonly Property PACKNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Packing Crates (No.)" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Packing Crates (No.)")>
    Public Property NUMPACK As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Order" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Order", length:=16)>
    Public Property ORDNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Ln" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Ln")>
    Public Property OLINE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Due Date" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Due Date", ReadOnly:=True)>
    Public Readonly Property ORDIDUEDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Requested Date" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Requested Date", ReadOnly:=True)>
    Public Readonly Property ORDIPRDATE As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Warehouse" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Warehouse", mandatory:=True, length:=4)>
    Public Property WARHSNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Bin" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bin", mandatory:=True, length:=14)>
    Public Property LOCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Budget Item" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Budget Item", ReadOnly:=True, length:=24)>
    Public Readonly Property BUDCODE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Profit Centre" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Profit Centre", length:=8)>
    Public Property COSTCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "From Status" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("From Status", mandatory:=True, length:=16)>
    Public Property CUSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "From Pallet" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("From Pallet", length:=16)>
    Public Property PALLETNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Inventory Date Code" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Inventory Date Code", ReadOnly:=True, length:=4)>
    Public Readonly Property DATECODE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Balance of Crates" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Balance of Crates", ReadOnly:=True)>
    Public Readonly Property PNUMPACK As Integer
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Key Line" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Key Line", Key:=True)>
    Public Property KLINE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Transaction (ID)" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Transaction (ID)")>
    Public Property TRANS As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Type" Value of TRANSORDER_A.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Type", Key:=True, length:=1)>
    Public Property TYPE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowTRANSORDER_A.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialTRANSORDER_A 

    Public Property PARTNAME As String
    Public Property PDES As String
    Public Property SERIALNAME As String
    Public Property SERIALDES As String
    Public Property BARCODE As String
    Public Property REVNAME As String
    Public Property REVNUM As String
    Public Property CUSTPARTNAME As String
    Public Property CUSTPARTBARCODE As String
    Public Property CQUANT As Decimal?
    Public Property PQUANT As Decimal?
    Public Property SETFLAG As String
    Public Property TQUANT As Decimal?
    Public Property TUNITNAME As String
    Public Property QUANT As Decimal?
    Public Property UNITNAME As String
    Public Property PACKCODE As String
    Public Property PACKNAME As String
    Public Property NUMPACK As Integer?
    Public Property ORDNAME As String
    Public Property OLINE As Integer?
    Public Property ORDIDUEDATE As Date?
    Public Property ORDIPRDATE As Date?
    Public Property WARHSNAME As String
    Public Property LOCNAME As String
    Public Property BUDCODE As String
    Public Property COSTCNAME As String
    Public Property CUSTNAME As String
    Public Property PALLETNAME As String
    Public Property DATECODE As String
    Public Property PNUMPACK As Integer?
    Public Property KLINE As Integer?
    Public Property TRANS As Integer?
    Public Property TYPE As String


End Class