Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: TRANSORDER_D as List(Of rowTRANSORDER_D)
''' Date: 20/03/2020
'''
''' </summary>
<oFormClass("rowTRANSORDER_D")>
Public Class TRANSORDER_D : Inherits oForm

    ''' <summary>
    ''' TRANSORDER_D Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the TRANSORDER_D form.
    ''' </summary>
    ''' <returns>rowTRANSORDER_D</returns>
    Public Function AddRow() As rowTRANSORDER_D
        With Me
            .Add(New rowTRANSORDER_D(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the TRANSORDER_D form.
''' </summary>
<oRowClass("TRANSORDER_D", "serialTRANSORDER_D")>
Public Class rowTRANSORDER_D : Inherits oRow

    ''' <summary>
    ''' rowTRANSORDER_D Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Part Number" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Number", mandatory:=True, length:=15)>
    Public Property PARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Description" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Description", length:=48)>
    Public Property PDES As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Balance to Ship" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Balance to Ship")>
    Public Property CQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Warehouse Balance" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Warehouse Balance", ReadOnly:=True)>
    Public Readonly Property PQUANT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Approve" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Approve", length:=1)>
    Public Property SETFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Quantity" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Quantity")>
    Public Property TQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Unit" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Unit", ReadOnly:=True, length:=3)>
    Public Readonly Property TUNITNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Unit Price" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Unit Price")>
    Public Property PRICE As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Item Currency" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Item Currency", mandatory:=True, length:=3)>
    Public Property ICODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Price Source" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Price Source", ReadOnly:=True, length:=16)>
    Public Readonly Property PRSOURCENAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Discount%" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Discount%")>
    Public Property PERCENT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Extended Price" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Extended Price", ReadOnly:=True)>
    Public Readonly Property QPRICE As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Document Currency" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Document Currency", ReadOnly:=True, length:=3)>
    Public Readonly Property CODE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Minimum Price" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Minimum Price", ReadOnly:=True)>
    Public Readonly Property MINPRICE As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Work Order/Lot" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Work Order/Lot", mandatory:=True, length:=22)>
    Public Property SERIALNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Work Order/Lot Desc." Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Work Order/Lot Desc.", ReadOnly:=True, length:=48)>
    Public Readonly Property SERIALDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Bar Code" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bar Code", length:=16)>
    Public Property BARCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "BOM Revision Number" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("BOM Revision Number", ReadOnly:=True, length:=3)>
    Public Readonly Property REVNUM As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Part Revision No." Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Revision No.", length:=10)>
    Public Property REVNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Cust. Part Number" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Cust. Part Number", length:=15)>
    Public Property CUSTPARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Customer Bar Code" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Customer Bar Code", length:=16)>
    Public Property CUSTPARTBARCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "From Status" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("From Status", mandatory:=True, length:=16)>
    Public Property CUSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "To Status" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("To Status", mandatory:=True, length:=16)>
    Public Property TOCUSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Cust's Order" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Cust's Order", ReadOnly:=True, length:=15)>
    Public Readonly Property ORDREFERENCE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Cust's Order Ln" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Cust's Order Ln", ReadOnly:=True)>
    Public Readonly Property YOURORDLINE As Integer
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Qty (Factory Units)" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Qty (Factory Units)")>
    Public Property QUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Factory Unit" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Factory Unit", ReadOnly:=True, length:=3)>
    Public Readonly Property UNITNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Packing Crates (No.)" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Packing Crates (No.)")>
    Public Property NUMPACK As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Crate Type Code" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Crate Type Code", length:=2)>
    Public Property PACKCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Crate Number" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Crate Number", length:=8)>
    Public Property CARTONNUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Order" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Order", length:=16)>
    Public Property ORDNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Ln" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Ln")>
    Public Property OLINE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Pallet" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Pallet", length:=16)>
    Public Property PALLETNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Inventory Date Code" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Inventory Date Code", ReadOnly:=True, length:=4)>
    Public Readonly Property DATECODE As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Due Date" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Due Date", ReadOnly:=True)>
    Public Readonly Property DUEDATEOI As Date
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Billable?" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Billable?", length:=1)>
    Public Property FLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Checking" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Checking", length:=1)>
    Public Property CHECKING As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Invoice" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Invoice", ReadOnly:=True, length:=16)>
    Public Readonly Property IVNUM As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Warehouse" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Warehouse", mandatory:=True, length:=4)>
    Public Property WARHSNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Bin" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bin", mandatory:=True, length:=14)>
    Public Property LOCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Site" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Site", length:=4)>
    Public Property DSTCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Site Description" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Site Description", ReadOnly:=True, length:=32)>
    Public Readonly Property CODEDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "To Warehouse" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("To Warehouse", length:=4)>
    Public Property TOWARHSNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Bin" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bin", length:=14)>
    Public Property TOLOCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "To Pallet" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("To Pallet", length:=16)>
    Public Property TOPALLETNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "On Loan" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("On Loan", length:=1)>
    Public Property ONLOAN As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Budget Item" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Budget Item", length:=24)>
    Public Property BUDCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Profit Centre" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Profit Centre", length:=8)>
    Public Property COSTCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Exchange Rate" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Exchange Rate")>
    Public Property EXCH As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Line Reference" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Line Reference", length:=16)>
    Public Property TRANSREFERENCE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Balance of Crates" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Balance of Crates", ReadOnly:=True)>
    Public Readonly Property PNUMPACK As Integer
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Base Product No." Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Base Product No.", length:=15)>
    Public Property MPARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Base Product Desc." Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Base Product Desc.", ReadOnly:=True, length:=48)>
    Public Readonly Property MPARTDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Part by Base Product" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part by Base Product", length:=15)>
    Public Property MMPARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Acceptable" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Acceptable", ReadOnly:=True, length:=1)>
    Public Readonly Property ANALYSISVALID As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Unacceptable" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Unacceptable", ReadOnly:=True, length:=1)>
    Public Readonly Property ANALYSISNOTVALID As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "VAT?" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("VAT?", length:=1)>
    Public Property VATFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Key Line" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Key Line", Key:=True)>
    Public Property KLINE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Transaction (ID)" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Transaction (ID)")>
    Public Property TRANS As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Type" Value of TRANSORDER_D.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Type", Key:=True, length:=1)>
    Public Property TYPE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowTRANSORDER_D.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialTRANSORDER_D 

    Public Property PARTNAME As String
    Public Property PDES As String
    Public Property CQUANT As Decimal?
    Public Property PQUANT As Decimal?
    Public Property SETFLAG As String
    Public Property TQUANT As Decimal?
    Public Property TUNITNAME As String
    Public Property PRICE As Decimal?
    Public Property ICODE As String
    Public Property PRSOURCENAME As String
    Public Property PERCENT As Decimal?
    Public Property QPRICE As Decimal?
    Public Property CODE As String
    Public Property MINPRICE As Decimal?
    Public Property SERIALNAME As String
    Public Property SERIALDES As String
    Public Property BARCODE As String
    Public Property REVNUM As String
    Public Property REVNAME As String
    Public Property CUSTPARTNAME As String
    Public Property CUSTPARTBARCODE As String
    Public Property CUSTNAME As String
    Public Property TOCUSTNAME As String
    Public Property ORDREFERENCE As String
    Public Property YOURORDLINE As Integer?
    Public Property QUANT As Decimal?
    Public Property UNITNAME As String
    Public Property NUMPACK As Integer?
    Public Property PACKCODE As String
    Public Property CARTONNUM As String
    Public Property ORDNAME As String
    Public Property OLINE As Integer?
    Public Property PALLETNAME As String
    Public Property DATECODE As String
    Public Property DUEDATEOI As Date?
    Public Property FLAG As String
    Public Property CHECKING As String
    Public Property IVNUM As String
    Public Property WARHSNAME As String
    Public Property LOCNAME As String
    Public Property DSTCODE As String
    Public Property CODEDES As String
    Public Property TOWARHSNAME As String
    Public Property TOLOCNAME As String
    Public Property TOPALLETNAME As String
    Public Property ONLOAN As String
    Public Property BUDCODE As String
    Public Property COSTCNAME As String
    Public Property EXCH As Decimal?
    Public Property TRANSREFERENCE As String
    Public Property PNUMPACK As Integer?
    Public Property MPARTNAME As String
    Public Property MPARTDES As String
    Public Property MMPARTNAME As String
    Public Property ANALYSISVALID As String
    Public Property ANALYSISNOTVALID As String
    Public Property VATFLAG As String
    Public Property KLINE As Integer?
    Public Property TRANS As Integer?
    Public Property TYPE As String


End Class